### ISSUE TITLE
Crashing when trying to access schematic Tabs

### ISSUE THREAD

**Issue by Rovstam** [Ferlern/extended-UI-v7#14]
I started clicking randomly at the images so i could set a schem but i could not find what i was wanting, then i started clicking on the icons fast and it crashed, leaving this message in the screen. Now everytime i try to access that tab, the game crashes and the same message pops up.
![2023-07-21 11_23_26-Window](https://github.com/Ferlern/extended-UI-v7/assets/124090007/1d2c28ae-f308-4da4-b2a8-bb5a97ff1e84)

**Comment by Ferlern** [comment]
I don't understand how this error is possible and I was unable to recreate it.
Since the settings causing the error have been lost, there is no way to debug

The error is specific and unlikely, therefore, until the next occurrence, lets assume that there is no such error
